<a href="https://colab.research.google.com/github/NguyenGiaDatt20104004/Nguyen-Gia-Dat-20104004/blob/main/AI2_(15112022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ResNet50

In [ ]:
#import tensorflow as tf
#import numpy as np

In [ ]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

model = ResNet50(weights='imagenet')

img_path = '/content/cho-con.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])
# Predicted: [(u'n02504013', u'Indian_elephant', 0.82658225), (u'n01871265', u'tusker', 0.1122357), (u'n02504458', u'African_elephant', 0.061040461)]

1/1 [==============================] - 1s 1s/step
Predicted: [('n02113023', 'Pembroke', 0.98463285), ('n02088364', 'beagle', 0.00797142), ('n02113186', 'Cardigan', 0.004248169)]


In [ ]:
#VGG16
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)

img_path = 'husky.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)
print('Predicted:', preprocess_input(x))

1/1 [==============================] - 1s 722ms/step
Predicted: [[[[-194.619 -193.558 -218.619]
   [-197.619 -197.558 -219.619]
   [-200.619 -201.558 -218.619]
   ...
   [-183.619 -180.558 -201.619]
   [-185.619 -184.558 -211.619]
   [-185.619 -184.558 -211.619]]

  [[-193.619 -192.558 -217.619]
   [-194.619 -194.558 -216.619]
   [-197.619 -197.558 -217.619]
   ...
   [-183.619 -180.558 -201.619]
   [-185.619 -184.558 -209.619]
   [-185.619 -184.558 -209.619]]

  [[-188.619 -187.558 -214.619]
   [-192.619 -191.558 -216.619]
   [-196.619 -196.558 -216.619]
   ...
   [-184.619 -181.558 -202.619]
   [-185.619 -184.558 -209.619]
   [-185.619 -184.558 -209.619]]

  ...

  [[ -84.619 -112.558 -164.619]
   [ -86.619 -118.558 -161.619]
   [ -84.619 -109.558 -162.619]
   ...
   [ -71.619 -109.558 -142.619]
   [ -78.619 -116.558 -151.619]
   [ -84.619 -117.558 -154.619]]

  [[ -86.619 -113.558 -164.619]
   [ -86.619 -116.558 -156.619]
   [ -72.619  -97.558 -147.619]
   ...
   [ -73.619 -103.558 