<a href="https://colab.research.google.com/github/NguyenGiaDatt20104004/Nguyen-Gia-Dat-20104004/blob/main/AI_(111022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""ANN-ARTIFICIAL NEURAL NETWORK"""

In [ ]:
#1 Perception - Binary Network - Classification
#Multi Layer Perception 
#ANN
#CNN (convolutional NN)
#RNN
#Natural Language Processing
#Pre - Trained Network (Yolo)

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron

x = [[0,0], [1,0], [0,1], [1,1]]
y = [0, 1, 1, 1]

model = Perceptron()
model.fit(x,y)
print("Độ chính xác: ", model.score(x,y))

x_test = [[0,0.5], [0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

Độ chính xác:  1.0
[0 1 0 1]


In [ ]:
x = [[-0.5,-0.5], [-0.5,0.5], [0.3,-0.5], [-0.1,1]]
y = [1,1,0,0]

model = Perceptron()
model.fit(x,y)
print("Độ chính xác: ", model.score(x,y))

x_test = [[1,0], [0,1],[1,1],[-0.5,0.5]]
y_test = model.predict(x_test)
print(y_test)

Độ chính xác:  1.0
[0 0 0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "crabs.csv"
data = pd.read_csv(url)
x_data = data[data["speies"]=="B"]
x = x_data.drop(x.columns[[0,1,2]], axis=1)

y_data = data[data["speies"]=="B"]
y = y_data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[8.1,6.7,16.1,19,7], [7.2,6.5,14.7,17.1,6.1]]
y_pred = model.predict(x_input)

print(y_pred)


Độ chính xác:  0.8714285714285714
[1 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "crabs.csv"
data = pd.read_csv(url)
x_data = data[data["speies"]=="B"]
x = x_data.drop(x.columns[[0,1,2]], axis=1)

y_data = data[data["speies"]=="B"]
y = y_data["sex"].replace(["M","F"],[1,0])
y = np.array(y)
y=y.T

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[8.1,6.7,16.1,19,7], [7.2,6.5,14.7,17.1,6.1]]
y_pred = model.predict(x_input)

print(y_pred)


Độ chính xác:  0.9142857142857143
[1 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = '/content/iris.csv'
data = pd.read_csv(url)
data = data[:100]
x= data.drop(['variety'],axis = True)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác: ', model.score(x_train,y_train))
x_input = [[5,3,1.6,0.2],[5,3.4,1.6,0.4],[7,3.2,4.7,1.4]]
y_pred = model.predict(x_input)
print(y_pred)

Độ chính xác:  1.0
[1 1 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
